Documentatie v1.0
threedi/hhnk-threedi-plugin pull request #157
Opened 2023-12-28 13:11 UTC by wvanesse

Hi Wietse, Jelle,

ik heb de documentatie van o.a. SAWA helemaal geleen en redelijk veel omgeschreven. Het is nog niet compleet. Ik mis bijvoorbeeld nog een stukje over de HDB, maar voor de plugin is het een complete handleiding en voor de modellen een redelijk naslagwerk. Leuk detail is dat we de tabel met formules die Michael voor de waterdiepte heeft gebruikt nog gevonden hebben. Voor de datachecker en modelbuilder ontbreekt een gebruikshandleiding.

Op een aantal punten staat commentaar met vragen die ik niet kan beantwoorden. Ik heb ze zoveel mogelijk gelabeled met 'TODO'. Willen jullie daar in ieder geval naar kijken?

Ten slotte weet ik niet precies hoe het op de git pagina er uit komt te zien. Op de home van de repo staat een link en een inhoudsopgave. Ook staat daar een link naar de installatiehandleiding waar in ook ergens naar verwijs. Ik weet niet of dat allemaal goed gaat. Willen jullie daar naar kijken?

Als ik de komende week nog iets toevoeg maak ik een nieuwe commit in deze branch. Dan dus graag de laatste commit uit deze branch gebruiken.

Grüße,
Wouter

2024-02-13 17:26 UTC, wvangerwen commented on docs/md_files/2_werkwijze_bwn/werkwijze_bwn.md
> +In het BWN2-project is sprake van referentiemodellen en maatregelmodellen. Zoals de naam doet vermoeden gaat het in de referentiemodellen om de referentie situatie; het watersysteem zoals dit er op d
link modellenregister?

2024-02-27 18:11 UTC, wvangerwen requested changes

2024-02-27 18:11 UTC, wvangerwen commented on docs/md_files/3_achtergronden_en_uitgangspunten/e_onderliggende_rasterdata/1_onderliggende_rasterdata.md
> +Tijdens het BWN2-project zijn bergingskaarten gebaseerd op de Alterra grondwaterstanden en bergingscoëfficiënten uit SOBEK. HHNK werkt aan het verbeteren van de input voor de bodembergingskaarten voo
Dit soort haakjes in tekst zetten dat er aan gewerkt wordt op zich prima, maar hoe zorgen we er dan voor dat we dit ook goed bijwerken als we er daadwerkelijk wat aan gedaan hebben?

2024-02-27 18:12 UTC, wvangerwen requested changes
Review eerste 3 hoofdstukken

2024-02-27 18:14 UTC, wvangerwen commented on docs/md_files/3_achtergronden_en_uitgangspunten/e_onderliggende_rasterdata/1_onderliggende_rasterdata.md
> +Tijdens het BWN2-project zijn bergingskaarten gebaseerd op de Alterra grondwaterstanden en bergingscoëfficiënten uit SOBEK. HHNK werkt aan het verbeteren van de input voor de bodembergingskaarten voo
opgelost met <sup>

2024-02-29 12:31 UTC, wvanesse commented on docs/md_files/2_werkwijze_bwn/werkwijze_bwn.md
> +In het BWN2-project is sprake van referentiemodellen en maatregelmodellen. Zoals de naam doet vermoeden gaat het in de referentiemodellen om de referentie situatie; het watersysteem zoals dit er op d
Ik heb het modellenregister op E gezet en er een link naar toegevoegd

2024-02-29 12:31 UTC, wvanesse commented on docs/md_files/2_werkwijze_bwn/werkwijze_bwn.md
> +Met klimaatsommen wordt een set van [18 stochasten](..\3_achtergronden_en_uitgangspunten\g_achtergrond_klimaatsommen\1_achtergrond_klimaatsommen.md) bedoeld waarmee het watersysteem op extreme neersl
aangepast

2024-02-29 12:31 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/g_achtergrond_klimaatsommen/1_achtergrond_klimaatsommen.md
> +![Alt text](../../../images/3_achtergronden_en_uitgangspunten/g_klimaatsommen/neerslag_piek_blok.png)<br>
aangepast

2024-02-29 12:32 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/b_logisch_bereik/1_logisch_bereik.md
> +![Logisch bereik en aannames](../../../images/3_achtergronden_en_uitgangspunten/Tabel_logisch_bereik_.png)
ja, stond er al in maar op net een andere plek. Heb een verwijzing toegevoegd. Ik weet niet hoe ik hem als download beklikbaar maak, maar volgens mij prima zo.

2024-02-29 12:32 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/c_watergangen_en_peilgebieden/1_initieel_peil.md
> +Als de peil_wsa kolom niet is ingevuld, wordt het streefpeil volgens bovenstaande lijst bepaald of wordt er gebruik gemaakt van de aanname NAP -10m.
aangepast

2024-02-29 12:35 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/c_watergangen_en_peilgebieden/2_levees.md
> +
jawel, maar werden nog niet gebruikt in modelbuilder. Inmiddels wel. 
15cecd776c18823e9827df643888bd083f530bc2

2024-02-29 12:39 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/c_watergangen_en_peilgebieden/4_profiel.md
> +* Datachecker crossprofile hoogte mag niet 0,0 zijn
aangepast

2024-02-29 12:40 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/c_watergangen_en_peilgebieden/4_profiel.md
> +* Profielen niet in geheel verlagen maar alleen een smal segment in het midden.
Ik denk dat hier nu niets mee gebeurd in de modelbuilder. Worden gewoon naar beden gezet met aannames denk ik. Ik voor een soort disclaimer toe.

2024-02-29 12:52 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/c_watergangen_en_peilgebieden/5_compensatie_te_weinig_oppervlaktewaterberging.md
> +De berging in 1D (connection nodes + profielen watergangen) wordt per peilgebied vergeleken met het oppervlak van de BGT-waterdelen (vlakken). Een tekort aan berging wordt gelijk verdeeld toegekend a
aangepast,
en ja, issue?

2024-02-29 15:11 UTC, wvanesse commented on docs/md_files/4_gebruik_plugin/h_banklevel_test.md
> +Het draaien van de bank levels test kan worden gedaan met elk 3Di resultaat zolang het rekengrid niet is veranderd. De inhoud van het scenario is hierbij niet relevant.
ja top, heb het nog even getest. aangepast

2024-02-29 15:34 UTC, wvanesse commented on docs/md_files/4_gebruik_plugin/h_banklevel_test.md
> +* De derde situatie die zich voor kan doen is dat er geen 1d2d verbinding kruist met een levee of fixeddrainagelevelarea. De banklevel is in dit geval ook gelijk aan het streefpeil + 10cm. Het streef
aangepast

2024-02-29 15:36 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/2_bruggen.md
> +In 3Di worden wel energie verliezen meegenomen voor het smaller of breder worden van het stroomprofiel.
Voor de discharege coeff? Die staat niet in DAMO

2024-02-29 15:47 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/3_duikers.md
> +Indien er geen data beschikbaar is wordt er een waarde aangenomen van rond de 0.5 meter, bob op streefpeil minus duikerhoogte.
aangepast

2024-02-29 15:55 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/3_duikers.md
> +![Alt text](../../../images/3_achtergronden_en_uitgangspunten/Duikers_op_peil(afwijking)grens.png)
het commentaar staat niet op de juiste regel, ik heb het 4e punt weggehaald.

2024-02-29 15:57 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/3_duikers.md
> +![Alt text](../../../images/3_achtergronden_en_uitgangspunten/Duikers_op_peil(afwijking)grens.png)
was niet duidelijk, aangepast

2024-02-29 15:57 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/3_duikers.md
> +![Alt text](../../../images/3_achtergronden_en_uitgangspunten/Duikers_op_peil(afwijking)grens.png)
ja maar dat was handwerk toch?

2024-02-29 15:59 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/3_duikers.md
> +![Alt text](../../../images/3_achtergronden_en_uitgangspunten/Duikers_op_peil(afwijking)grens.png)
toegevoegd

2024-02-29 15:59 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/4_gemalen.md
> +Het aan- en afslagpeil is gebaseerd op het streefpeil lage zijde (afvoeraanname). Dit gaat niet goed bij aanvoer-gemalen, maar omdat die een capaciteit van 0 meekrijgen heeft dit geen effect in de mo
toegevoegd

2024-02-29 16:02 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/5_stuwen.md
> +Bij een stuw op het uiteinde van een duiker, komt alleen de stuw in het model met het profiel van de stuw.
aangepast en breedte toegevoegd

2024-02-29 16:02 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/5_stuwen.md
> +Bij een stuw op het uiteinde van een duiker, komt alleen de stuw in het model met het profiel van de stuw.
?

2024-02-29 16:03 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/5_stuwen.md
> +Bij een stuw op het uiteinde van een duiker, komt alleen de stuw in het model met het profiel van de stuw.
WS_FUNCTIESTUW toegevoegd, ik kan weer niet zien welke regel je precies bedoelt.

2024-02-29 16:05 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/d_kunstwerken/5_stuwen.md
> +Bij een stuw op het uiteinde van een duiker, komt alleen de stuw in het model met het profiel van de stuw.
ik maak een aparte pagina, maar kom er nu niet aan toe die te vullen.

2024-02-29 16:08 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/e_onderliggende_rasterdata/1_onderliggende_rasterdata.md
> +2. Maaiveldcorrecties door te voeren voor bouwputten, inritten, tunnelbakken en maaiveldveranderingen (bv recent aangelegde waterberging);
aangepast.

2024-02-29 16:16 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/e_onderliggende_rasterdata/1_onderliggende_rasterdata.md
> +Tijdens het BWN2-project zijn bergingskaarten gebaseerd op de Alterra grondwaterstanden en bergingscoëfficiënten uit SOBEK. HHNK werkt aan het verbeteren van de input voor de bodembergingskaarten voo
toegevoegd

2024-02-29 16:19 UTC, wvanesse commented on docs/md_files/3_achtergronden_en_uitgangspunten/e_onderliggende_rasterdata/1_onderliggende_rasterdata.md
> +Tijdens het BWN2-project zijn bergingskaarten gebaseerd op de Alterra grondwaterstanden en bergingscoëfficiënten uit SOBEK. HHNK werkt aan het verbeteren van de input voor de bodembergingskaarten voo
aangepast

2024-02-29 16:21 UTC, wvanesse commented
Hi Wietse, meeste heb ik aangepast in een nieuwe commit. Wat mij betreft zetten we deze online.

2024-03-18 09:44 UTC, wvangerwen commented on docs/md_files/4_gebruik_plugin/z_bekende_problemen.md
> +## **Bekende problemen**
Deze kan wel blijven bestaan, maar helemaal leeg gemaakt? Want dit is opgelost.

2024-03-18 09:49 UTC, wvangerwen commented on docs/md_files/originele_md_files/tests_documentation.md
> +# Uitleg tests en functionaliteit
Moet ik hier ook naar kijken?

2024-10-01 12:12 UTC, wvangerwen approved these changes
Staan nog een aantal TODO's in maar die komen we wel met de tijd wel tegen.

2024-10-01 12:13 UTC, merged